In [84]:
import pandas as pd
import numpy as np
import re

In [85]:
df=pd.read_csv('C:\\Users\\spart\\Desktop\\Datascience\\NLP\\IMDB Dataset.csv\\IMDB Dataset.csv')

In [86]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [87]:
def remove_html_tag(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',text)

In [88]:
df['review']=df['review'].apply(remove_html_tag)

In [89]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [90]:
df['review']=df['review'].str.lower()
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [91]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [92]:
df['review']=df['review'].apply(remove_url)

In [93]:
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [94]:
import string

In [95]:
exclude=string.punctuation

In [96]:

def remove_punctuation(text):
    return text.translate(str.maketrans('','',exclude))

In [97]:
df['review']=df['review'].apply(remove_punctuation)

In [98]:
df['review'][1]

'a wonderful little production the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done'

In [99]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [100]:
def remove_stopwords(text):
    stop_words_set = set(stopwords.words('english'))
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words_set]
    return " ".join(filtered_words)

In [101]:
df['review']=df['review'].apply(remove_stopwords)


In [102]:
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically theres family little boy jake thinks...
4        petter matteis love time money visually stunni...
                               ...                        
49995    thought movie right good job wasnt creative or...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    im going disagree previous comment side maltin...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 50000, dtype: object

In [103]:
df.duplicated().sum()

422

In [104]:
df.drop_duplicates(inplace=True)

In [105]:
df['sentiment'].value_counts()

sentiment
positive    24883
negative    24695
Name: count, dtype: int64

In [106]:
df

review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production filming technique ...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically theres family little boy jake thinks...  negative
4      petter matteis love time money visually stunni...  positive
...                                                  ...       ...
49995  thought movie right good job wasnt creative or...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  catholic taught parochial elementary schools n...  negative
49998  im going disagree previous comment side maltin...  negative
49999  one expects star trek movies high art fans exp...  negative

[49578 rows x 2 columns]

In [107]:
X=df.iloc[::4,0:1]
Y=df['sentiment'][::4]

In [108]:
X

review
0      one reviewers mentioned watching 1 oz episode ...
4      petter matteis love time money visually stunni...
8      encouraged positive comments film looking forw...
12     im big fan bolls work many enjoyed movie posta...
16     films simply remade one bad film fails capture...
...                                                  ...
49979  saw high expectations come akshay kumar govind...
49983  loved fan original series always wondered back...
49989  got one weeks ago love modern light filled tru...
49994  typical junk comedythere almost laughs genuine...
49998  im going disagree previous comment side maltin...

[12395 rows x 1 columns]

In [109]:
Y.shape

(12395,)

In [110]:
from sklearn.preprocessing import LabelEncoder

In [111]:
Y=LabelEncoder().fit_transform(Y)
Y

array([1, 1, 0, ..., 1, 0, 0])

In [112]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [113]:
X_train.shape

(9916, 1)

In [114]:
from sklearn.feature_extraction.text import CountVectorizer


In [115]:
cv=CountVectorizer()

In [116]:
X_test

review
22033  instead writing paragraph ill give four good r...
43860  film eluded thus far ive watched emerges one m...
3452   sentinel movie recommended years ago father iv...
5155   spoilers understand really happened first warr...
15628  first sidestory universal century gundam unive...
...                                                  ...
39330  well target market loved furthermore husband a...
34825  live salt lake city im mormon rent movie well ...
38505  fondlyremembered melodrama – thanks chiefly ro...
9985   soylent green found excellent movieif like log...
31768  one many speculations y2k world going end stro...

[2479 rows x 1 columns]

In [117]:
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

In [118]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

gnb.fit(X_train_bow,Y_train)

GaussianNB()

In [119]:
Y_predict=gnb.predict(X_test_bow)

In [120]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(Y_test,Y_predict)

0.6462283178701089

In [121]:
confusion_matrix(Y_test,Y_predict)

array([[912, 348],
       [529, 690]], dtype=int64)

In [122]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train_bow,Y_train)
Y_predict=rf.predict(X_test_bow)
accuracy_score(Y_test,Y_predict)

0.8438886647841872

In [123]:
confusion_matrix(Y_test,Y_predict)

array([[1066,  194],
       [ 193, 1026]], dtype=int64)

In [125]:
cv=CountVectorizer(ngram_range=(1,3),max_features=1000)
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()
rf=RandomForestClassifier()
rf.fit(X_train_bow,Y_train)
Y_predict=rf.predict(X_test_bow)
accuracy_score(Y_test,Y_predict)

0.8229124647035094

In [126]:
from sklearn.feature_extraction.text import TfidfVectorizer
Tfidf=TfidfVectorizer()

In [128]:
X_train_tfidf=Tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf=Tfidf.transform(X_test['review']).toarray()

In [129]:
rf=RandomForestClassifier()
rf.fit(X_train_tfidf,Y_train)
Y_predict=rf.predict(X_test_tfidf)
accuracy_score(Y_test,Y_predict)

0.8414683340056475

In [130]:
import gensim 
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [131]:
story=[]
for doc in df['review']:
    raw_sent =sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [133]:
model=gensim.models.Word2Vec(
    window=10,
    min_count=2,
    vector_size=300
)

In [134]:
model.build_vocab(story)

In [135]:
model.train(story,total_examples=model.corpus_count,epochs=100)

(553538579, 586723700)

In [136]:
len(model.wv.index_to_key)

79935

In [137]:
def document_vector(doc):
    doc=[word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc],axis=0)

In [138]:
from tqdm import tqdm 

In [139]:
X=[]
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 49578/49578 [23:19<00:00, 35.43it/s]


In [ ]:
X=np.array(X)


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [ ]:
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)
Y_predict=rf.predict(X_test)
accuracy_score(Y_test,Y_predict)